### ISSUE TITLE
1xx status codes not getting through

### ISSUE THREAD

**Issue by ahosie** [Readify/httpstatus#75] opened 2019-12-09 06:36 UTC
I'm getting a 502 error on any requests for status codes 100 - 103.

![image](https://user-images.githubusercontent.com/11976274/70412999-591c2280-1aaa-11ea-9c5d-3d5795afe0e5.png)

Looks a lot like an IIS error page. I'm thinking Azure is getting in the middle of things?

**Comment by RobFaie** [comment] 2020-01-17 09:56
Duplicate of #48

**Closed by RobFaie** 2020-01-17 09:56 UTC
